- name: database file expenses
  hosts: db
  become: yes
  vars: 
    login_host: 172.31.28.22
  vars_prompt:
  - name: my_root_password
    prompt: Please enter the password
    private: no
  tasks:
    - name: installation of mysql server
      ansible.builtin.dnf:
        name: mysqld
        state: latest
    - name: starting and enable of mysql server 
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes
    - name: check DB connection
      community.mysql.mysql_info:
        login_user: root
        login_password: ExpenseApp@1
        login_host: {{login_host}}
        filter: version
      ignore_errors: yes
      register: database_connection_output

    - name: The error log
      ansible.builtin.debug:
        msg: "The error is: {{database_connection_output}}"

    # - name: setting up the root password
    #   ansible.builtin.command: sql_secure_installation --set-root-pass {{my_root_password}}